const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,DATA=path.join(ROOT,'data'),CONFIG=path.join(ROOT,'config');
fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(CONFIG,{recursive:true});
const F=n=>path.join(DATA,n), C=n=>JSON.parse(fs.readFileSync(path.join(CONFIG,n),'utf8'));
function R(n,d){try{return fs.existsSync(F(n))?JSON.parse(fs.readFileSync(F(n),'utf8')):d}catch{return d}} function W(n,v){fs.writeFileSync(F(n),JSON.stringify(v,null,2))}
let players=R('players.json',[]),nextPlayer=R('nextPlayerId.json',{nextId:1}).nextId,nextChar=R('nextCharacterId.json',{nextId:1}).nextId;
const banks=C('banks.json'),factions=C('factions.json'),events=C('events.json'),vehicles=C('vehicles.json'),properties=C('properties.json'),businesses=C('businesses.json'),pets=C('pets.json'),shops=C('shops.json');
const started=Date.now(),save=()=>{W('players.json',players);W('nextPlayerId.json',{nextId:nextPlayer});W('nextCharacterId.json',{nextId:nextChar})};
const acct=id=>players.find(a=>a.accountId===id), chr=(a,id)=>a&&a.characters.find(c=>String(c.characterId)===String(id));
function send(r,s,b){r.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS','Cache-Control':'no-store'});r.end(JSON.stringify(b))}
function body(q){return new Promise((ok,no)=>{let s='';q.on('data',x=>s+=x);q.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch{no(Error('Invalid JSON'))}});q.on('error',no)})}
const taken=(n,ex)=>players.some(a=>a.characters.some(c=>c.name.toLowerCase()===n.toLowerCase()&&c.characterId!==ex));
function newChar(name,skin){return {characterId:nextChar++,name,skinId:skin||'skin_001',level:1,experience:0,money:0,seCoins:0,health:100,maxHealth:100,armor:0,maxArmor:100,hunger:100,food:100,faction:null,factionRank:0,vehicles:[],inventory:[],bankAccounts:[],properties:[],businesses:[],pets:[],jobs:[],missions:[],eventHistory:[],position:{x:0,y:0,z:0},statistics:{playSeconds:0,jobsCompleted:0,eventsCompleted:0,kills:0,deaths:0},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
async function route(q,r){
 if(q.method==='OPTIONS'){r.writeHead(204);return r.end()} const p=new URL(q.url,'http://x').pathname;
 if(q.method==='GET'&&p==='/')return send(r,200,{name:'Supreme Empire',status:'online',message:'Server is running'});
 if(q.method==='GET'&&p==='/health')return send(r,200,{status:'ok',uptimeSeconds:Math.floor((Date.now()-started)/1000)});
 if(q.method==='GET'&&p==='/api/status')return send(r,200,{name:'Supreme Empire',status:'online',serverTime:new Date().toISOString(),uptimeSeconds:Math.floor((Date.now()-started)/1000),onlinePlayers:0,totalPlayers:players.length,banks:banks.length,factions:factions.length,missionsOptional:true,events});
 if(q.method==='GET'&&p==='/api/config')return send(r,200,{banks,factions,events,vehicles,properties,businesses,pets,shops});
 if(q.method==='POST'&&p==='/api/account'){const a={accountId:'acct_'+crypto.randomUUID(),playerId:nextPlayer++,maxCharacters:5,activeCharacterId:null,characters:[],createdAt:new Date().toISOString()};players.push(a);save();return send(r,201,a)}
 let m=p.match(/^\/api\/account\/([^/]+)$/); if(q.method==='GET'&&m){const a=acct(decodeURIComponent(m[1]));return a?send(r,200,a):send(r,404,{error:'Account not found'})}
 m=p.match(/^\/api\/account\/([^/]+)\/characters$/); if(m){const a=acct(decodeURIComponent(m[1]));if(!a)return send(r,404,{error:'Account not found'});if(q.method==='GET')return send(r,200,a);if(q.method==='POST'){const b=await body(q),n=String(b.name||'').trim();if(a.characters.length>=5)return send(r,409,{error:'Character limit reached',maxCharacters:5});if(n.length<2||n.length>24)return send(r,400,{error:'Nickname must be 2-24 characters'});if(!/^[A-Za-z0-9_ ]+$/.test(n))return send(r,400,{error:'Invalid nickname'});if(taken(n))return send(r,409,{error:'Nickname already taken'});const c=newChar(n,b.skinId);a.characters.push(c);if(!a.activeCharacterId)a.activeCharacterId=c.characterId;save();return send(r,201,{success:true,character:c,account:a})}}
 m=p.match(/^\/api\/account\/([^/]+)\/characters\/([^/]+)(?:\/(data|save|select))?$/); if(m){const a=acct(decodeURIComponent(m[1])),c=chr(a,m[2]);if(!a)return send(r,404,{error:'Account not found'});if(!c)return send(r,404,{error:'Character not found'});const action=m[3];if(q.method==='GET')return send(r,200,{accountId:a.accountId,playerId:a.playerId,character:c});if(action==='select'&&q.method==='POST'){a.activeCharacterId=c.characterId;save();return send(r,200,{success:true,activeCharacterId:c.characterId,character:c})}if((action==='save'||action==='data')&&(q.method==='POST'||q.method==='PUT')){const b=await body(q);if(b.name&&b.name.toLowerCase()!==c.name.toLowerCase()&&taken(b.name,c.characterId))return send(r,409,{error:'Nickname already taken'});for(const k of ['name','skinId','level','experience','money','seCoins','health','maxHealth','armor','maxArmor','hunger','food','faction','factionRank','vehicles','inventory','bankAccounts','properties','businesses','pets','jobs','missions','eventHistory','position','statistics'])if(b[k]!==undefined)c[k]=b[k];c.updatedAt=new Date().toISOString();save();return send(r,200,{success:true,savedAt:c.updatedAt,character:c})}}
 send(r,404,{error:'Not Found'})
}
http.createServer((q,r)=>route(q,r).catch(e=>{console.error(e);if(!r.headersSent)send(r,500,{error:'Internal Server Error'})})).listen(PORT,'0.0.0.0',()=>console.log('Supreme Empire server listening on 0.0.0.0:'+PORT));
