const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),HOST='0.0.0.0',ROOT=__dirname,CONFIG=path.join(ROOT,'config'),DATA=path.join(ROOT,'data');fs.mkdirSync(DATA,{recursive:true});
const DB={players:path.join(DATA,'players.json'),nextPlayer:path.join(DATA,'nextPlayerId.json'),nextCharacter:path.join(DATA,'nextCharacterId.json'),activity:path.join(DATA,'activity.log')};
function readJson(f,d){try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):d}catch(e){console.error(e.message);return d}}
function writeJson(f,v){const t=f+'.tmp';fs.writeFileSync(t,JSON.stringify(v,null,2));fs.renameSync(t,f)}
function cfg(n,d){return readJson(path.join(CONFIG,n),d)} function now(){return new Date().toISOString()}
function log(type,data={}){fs.appendFileSync(DB.activity,JSON.stringify({timestamp:now(),type,...data})+'\n')}
let players=readJson(DB.players,[]),nextPlayerId=Number(readJson(DB.nextPlayer,{nextId:1}).nextId||1),nextCharacterId=Number(readJson(DB.nextCharacter,{nextId:1}).nextId||1);
function save(){writeJson(DB.players,players);writeJson(DB.nextPlayer,{nextId:nextPlayerId});writeJson(DB.nextCharacter,{nextId:nextCharacterId})}
function pid(){while(players.some(p=>p.playerId===nextPlayerId))nextPlayerId++;return nextPlayerId++} function cid(){while(players.some(p=>(p.characters||[]).some(c=>c.characterId===nextCharacterId)))nextCharacterId++;return nextCharacterId++}
function account(id){return players.find(p=>p.accountId===id)} function char(a,id){return a&&(a.characters||[]).find(c=>String(c.characterId)===String(id))}
function taken(n,except=null){n=String(n).trim().toLowerCase();return players.some(p=>(p.characters||[]).some(c=>c.name.toLowerCase()===n&&String(c.characterId)!==String(except)))}
function validName(n){return /^[A-Za-z0-9_ ]{2,24}$/.test(String(n).trim())}
function newChar(name,skin='skin_001'){return {characterId:cid(),name:String(name).trim(),skinId:skin,level:1,experience:0,money:0,seCoins:0,faction:null,factionRank:0,health:100,armor:0,hunger:100,bankAccounts:[],inventory:{},vehicles:[],properties:[],businesses:[],pets:[],jobs:[],missions:[],eventHistory:[],statistics:{playSeconds:0,jobsCompleted:0,eventsCompleted:0,kills:0,deaths:0},position:{x:0,y:0,z:0},phone:null,createdAt:now(),updatedAt:now()}}
function pub(c){return {characterId:c.characterId,name:c.name,skinId:c.skinId,level:c.level,experience:c.experience,money:c.money,seCoins:Number(c.seCoins||0),faction:c.faction,factionRank:c.factionRank,health:c.health,armor:c.armor,hunger:c.hunger,createdAt:c.createdAt,updatedAt:c.updatedAt}}
function full(c){return JSON.parse(JSON.stringify(c))} function pubAcc(a){return {accountId:a.accountId,playerId:a.playerId,maxCharacters:5,activeCharacterId:a.activeCharacterId,characters:(a.characters||[]).map(pub)}}
const banks=cfg('banks.json',[]),factions=cfg('factions.json',[]),events=cfg('events.json',[]),missions=cfg('missions.json',[]),vehicles=cfg('vehicles.json',[]),characters=cfg('characters.json',[]),properties=cfg('properties.json',[]),businesses=cfg('businesses.json',[]),pets=cfg('pets.json',[]),shops=cfg('shops.json',[]);const started=Date.now();
function send(res,status,b){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS','Cache-Control':'no-store'});res.end(JSON.stringify(b))}
function fail(res,s,m,x={}){return send(res,s,{error:m,...x})} function body(req){return new Promise((ok,no)=>{let r='';req.on('data',c=>{r+=c;if(r.length>2e6)no(new Error('Request body too large'))});req.on('end',()=>{if(!r.trim())return ok({});try{ok(JSON.parse(r))}catch(e){no(new Error('Invalid JSON'))}});req.on('error',no)})}
for(const a of players){a.maxCharacters=5;a.characters ||= [];for(const c of a.characters){c.seCoins=Number(c.seCoins||0);c.bankAccounts ||= [];c.inventory ||= {};c.vehicles ||= [];c.properties ||= [];c.businesses ||= [];c.pets ||= [];c.jobs ||= [];c.missions ||= [];c.eventHistory ||= [];c.statistics ||= {playSeconds:0,jobsCompleted:0,eventsCompleted:0,kills:0,deaths:0}}}save();
async function handle(req,res){if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname;
if(req.method==='GET'&&p==='/')return send(res,200,{name:'Supreme Empire',status:'online',version:'2.0',message:'Supreme Empire server is running'});
if(req.method==='GET'&&p==='/health')return send(res,200,{status:'ok',service:'Supreme Empire',uptimeSeconds:Math.floor((Date.now()-started)/1000)});
if(req.method==='GET'&&p==='/api/status')return send(res,200,{name:'Supreme Empire',status:'online',serverTime:now(),uptimeSeconds:Math.floor((Date.now()-started)/1000),onlinePlayers:0,totalPlayers:players.length,banks:banks.length,factions:factions.length,missionsOptional:true,events});
if(req.method==='GET'&&p==='/api/config')return send(res,200,{banks,factions,events,missions,vehicles,characters,properties,businesses,pets,shops});
if(req.method==='GET'&&p==='/api/players'){let out=[];for(const a of players)for(const c of a.characters||[])out.push({id:c.characterId,playerId:a.playerId,accountId:a.accountId,nickname:c.name,level:c.level,faction:c.faction});return send(res,200,out)}
if(req.method==='POST'&&p==='/api/account'){const a={accountId:`acct_${crypto.randomUUID()}`,playerId:pid(),maxCharacters:5,activeCharacterId:null,characters:[],createdAt:now(),updatedAt:now()};players.push(a);save();log('account_created',{accountId:a.accountId,playerId:a.playerId});return send(res,201,pubAcc(a))}
let m=p.match(/^\/api\/account\/([^/]+)$/);if(req.method==='GET'&&m){const a=account(decodeURIComponent(m[1]));return a?send(res,200,pubAcc(a)):fail(res,404,'Account not found')}
m=p.match(/^\/api\/account\/([^/]+)\/characters$/);if(req.method==='GET'&&m){const a=account(decodeURIComponent(m[1]));return a?send(res,200,pubAcc(a)):fail(res,404,'Account not found')}
if(req.method==='POST'&&m){const a=account(decodeURIComponent(m[1]));if(!a)return fail(res,404,'Account not found');let b;try{b=await body(req)}catch(e){return fail(res,400,e.message)}if((a.characters||[]).length>=5)return fail(res,409,'Character limit reached',{maxCharacters:5});const n=String(b.name||'').trim();if(!validName(n))return fail(res,400,'Nickname must be 2-24 characters and use only letters, numbers, spaces and underscores');if(taken(n))return fail(res,409,'Nickname already taken');const c=newChar(n,b.skinId||'skin_001');a.characters.push(c);if(!a.activeCharacterId)a.activeCharacterId=c.characterId;a.updatedAt=now();save();log('character_created',{accountId:a.accountId,playerId:a.playerId,characterId:c.characterId,nickname:c.name});return send(res,201,{success:true,character:full(c),account:pubAcc(a)})}
m=p.match(/^\/api\/account\/([^/]+)\/characters\/([^/]+)\/data$/);if(req.method==='GET'&&m){const a=account(decodeURIComponent(m[1]));if(!a)return fail(res,404,'Account not found');const c=char(a,decodeURIComponent(m[2]));if(!c)return fail(res,404,'Character not found');return send(res,200,{playerId:a.playerId,accountId:a.accountId,character:full(c)})}
m=p.match(/^\/api\/account\/([^/]+)\/characters\/([^/]+)\/select$/);if(req.method==='POST'&&m){const a=account(decodeURIComponent(m[1]));if(!a)return fail(res,404,'Account not found');const c=char(a,decodeURIComponent(m[2]));if(!c)return fail(res,404,'Character not found');a.activeCharacterId=c.characterId;a.updatedAt=c.updatedAt=now();save();return send(res,200,{success:true,activeCharacterId:c.characterId,character:full(c)})}
m=p.match(/^\/api\/account\/([^/]+)\/characters\/([^/]+)\/save$/);if(req.method==='POST'&&m){const a=account(decodeURIComponent(m[1]));if(!a)return fail(res,404,'Account not found');const c=char(a,decodeURIComponent(m[2]));if(!c)return fail(res,404,'Character not found');let b;try{b=await body(req)}catch(e){return fail(res,400,e.message)}if(b.name!==undefined){const n=String(b.name).trim();if(!validName(n))return fail(res,400,'Invalid nickname');if(n.toLowerCase()!==c.name.toLowerCase()&&taken(n,c.characterId))return fail(res,409,'Nickname already taken');c.name=n}const fields=['skinId','level','experience','money','seCoins','bankAccounts','inventory','vehicles','properties','businesses','pets','faction','factionRank','jobs','missions','eventHistory','statistics','position','health','armor','hunger','phone'];for(const f of fields)if(Object.prototype.hasOwnProperty.call(b,f))c[f]=b[f];c.updatedAt=a.updatedAt=now();save();log('character_saved',{accountId:a.accountId,playerId:a.playerId,characterId:c.characterId,fields:Object.keys(b)});return send(res,200,{success:true,savedAt:c.updatedAt,character:full(c)})}
m=p.match(/^\/api\/account\/([^/]+)\/characters\/([^/]+)\/position$/);if(req.method==='POST'&&m){const a=account(decodeURIComponent(m[1]));if(!a)return fail(res,404,'Account not found');const c=char(a,decodeURIComponent(m[2]));if(!c)return fail(res,404,'Character not found');let b;try{b=await body(req)}catch(e){return fail(res,400,e.message)}const x=Number(b.x),y=Number(b.y),z=Number(b.z);if(![x,y,z].every(Number.isFinite))return fail(res,400,'Invalid position');c.position={x,y,z};c.updatedAt=a.updatedAt=now();save();return send(res,200,{success:true,position:c.position,savedAt:c.updatedAt})}
return fail(res,404,'Not Found')}
http.createServer((req,res)=>handle(req,res).catch(e=>{console.error(e);if(!res.headersSent)fail(res,500,'Internal Server Error')})).listen(PORT,HOST,()=>console.log(`Supreme Empire server listening on ${HOST}:${PORT}`));
